name: ss_flexicadastre
description: "[FlexiCadastre] Namibia Mining Cadastre Portal"
schedule: weekly
pipeline:
  init:
    method: flexicadastre.crawler:layers
    params:
      url: http://portals.flexicadastre.com/southsudan/
      layers:
        - Oil Concessions
        - ' Large-Scale Mining Licenses'
        - ' Small-Scale Mining Licenses'
        - Reconnaissance Licenses
        - Exploration Licenses
        - ActiveLicenses
        - Applications
    handle:
      pass: layer
  layer:
    method: flexicadastre.crawler:layer
    handle:
      pass: feature
  feature:
    method: flexicadastre.parser:feature
    handle:
      commodity: commodity
      party: party
      pass: record
  record:
    method: db
    params:
      table: ss_flexicadastre
      unique: ['FeatureId']
  party:
    method: db
    params:
      table: ss_flexicadastre_party
      unique: ['FeatureId', 'Party', 'Share']
  commodity:
    method: db
    params:
      table: ss_flexicadastre_commodity
      unique: ['FeatureId', 'Commodity']
